### ISSUE TITLE
Is there a way to add calenday month (like postgresql does) and not 31 days?

### ISSUE THREAD

**Issue by KES777** [houseabsolute/DateTime.pm#108]
I notice different math in compare to postgresql:

Here How DateTime do caclulations:
```
DBG> $c->parse_date( $first->consumed_till )
DateTime 2020-10-31T23:59:59

DBG> $c->parse_date( $first->consumed_till )->add( months => 1 )
DateTime 2020-12-01T23:59:59
```

And here is calculation results by database:
```
tucha=> select '2020-10-31 23:59:59'::timestamptz +interval '1mon';
        ?column?        
------------------------
 2020-11-30 23:59:59+02
```

You can notice, that in both cases I add one month, but results are differ

**Comment by autarch** [comment]
See the DateTime::Duration docs on the "end_of_month" parameter.

```
perl -MDateTime -E 'say DateTime->new( year => 2020, month => 10, day => 31 )->add( months => 1, end_of_month => q{limit} )'
2020-11-30T00:00:00
```

**Comment by KES777** [comment]
>For positive durations, the "end_of_month" parameter defaults to wrap. For negative durations, the default is "preserve". This should match how most people "intuitively" expect datetime math to work.

It seems that `end_of_month` parameter should defaults to `limit`, because this match how most people expect math to work. For example if you pay bills on 31.03 the date for next bill will be 30.04, not 01.05. This is how accounting work over all world.

Also, as I have shown, most popular database uses `limit`. 

To not break changes we can do same thing as `Test2`: `use DateTime::V0` which will use modern defaults, like `use v5.24` or so.

**Comment by autarch** [comment]
A `DateTime::V2` is an interesting idea. I think there are a number of changes that might go in there, including:

* Change the duration end_of_month default.
* Replace all methods that change the object's state with things that clone, so for example `$dt->add` always returns a new object, and instead of `$dt->set_year` we'd have `$dt->with_year`.
* Rationalizing the delta/subtract methods a bit. The naming and such is a bit confusing, IMO.
* Lots of other things, including [some ideas I talked about on my blog ten years ago](https://blog.urth.org/2010/11/01/my-programming-related-todo-list/).

But that said, I question whether anyone would use this. Some of this is already available via [`DateTime::Moonpig`](https://metacpan.org/pod/DateTime::Moonpig). If you look at its reverse deps you'll see that it has very few downstream dependents. Maybe that doesn't mean anything.

If this is something you're interesting working on, I can invite you to my HouseAbsolute slack org's #datetim channel.

**Comment by KES777** [comment]
#99

**Comment by KES777** [comment]
>The "end_of_month" parameter must be either "wrap", "limit", or "preserve". This parameter specifies how date math that crosses the end of a month is handled.
