### ISSUE TITLE
Support separator in datetime() accessor?

### ISSUE THREAD

**Issue by bigpresh** [houseabsolute/DateTime.pm#54]
I, very often, find myself writing e.g. `$dt->ymd . ' ' . $dt->hms` to get a readable date and time; I know I'm very much not alone in that.

`$dt->datetime` gives almost what I'd need, but in the ISO-standard format e.g. `YYYY-MM-DDTHH:MM::SS`, which is a bit ugly and not user-friendly.

What I would really, really like would be the ability to pass a separator character to override the "T" - e.g. `$dt->datetime(' ')` (which would be somewhat consistent with how e.g. `$dt->hms` lets you specify which character should be used to join hours, minutes and seconds).

Or, alternatively, a `$dt->ymd_hms()` method which would default to a space - but it's probably simpler and cleaner not to add another method when what it would do could be trivially done as above.

If I raised a PR doing this, would it be likely to be accepted, or is this not a desired feature in core DateTime?  We could of course subclass it and do it ourselves, but it seems, to me, like something that would be widely useful in DateTime itself.  Opinions welcome!

**Comment by preaction** [comment]
When I need this, I usually end up using `strftime( '%Y-%m-%d %H:%M:%S' )` (as the most portable) or `strftime( '%F %T' )` (which I've had some trouble with on some machines).

Since both `ymd` and `hms` also take a separator character as an argument, it might be confusing: `datetime` takes a joiner for the two parts, but not joiners for inside the two parts? There's a line here, and I'm personally willing to say it's at one argument that specifies how the two parts are joined together, but others might have other opinions.

So this seems reasonable to me, provided this is where we draw the line.

**Comment by bigpresh** [comment]
I agree that supporting options to control the separators betwen the date and time parts, as well as between the date and time itself, would be taking it too far.
