### ISSUE TITLE
Add from_ymd() and from_datetime()

### ISSUE THREAD

**Issue by perlancar** [houseabsolute/DateTime.pm#56]
This is a parallel for epoch() & from_epoch(), very easy to implement, and will make life easier for users since they don't have to do regex acrobatics or involve a separate formatter module.

**Comment by autarch** [comment]
Could you provide some more details of exactly how you'd expect this API to work?

**Comment by perlancar** [comment]
It will be similar to from_epoch():

    $dt = DateTime->from_epoch(epoch => 1497571200);

    $dt = DateTime->from_ymd(ymd => '2017-06-16');

    $dt = DateTime->from_datetime(datetime => '2017-06-16T00:00:00');

**Comment by autarch** [comment]
Sorry for not responding sooner. I'd note that this is already quite possible using any number of DateTime::Format::* modules on CPAN. I'm not sure it's worthwhile to add this to DateTime itself, especially since I really don't want DateTime to go down the string parsing route, and I'm sure if I add the simplest version the next request will be to allow different separators, followed by something else, culminating in re-implementing something like Strptime parsing (which already has a DateTime::Format::Strptime module).

**Comment by autarch** [comment]
Closing this for the reasons stated in my last comment.
