### ISSUE TITLE
Suggest adding stringify()

### ISSUE THREAD

**Issue by yahermann** [houseabsolute/DateTime.pm#58]
Overloading to obtain the string version of a DateTime works well in most cases, but not all.  Full issue described and discussed here:

https://stackoverflow.com/questions/45469748/true-stringify-of-datetime

**Comment by autarch** [comment]
The question is a little confusing. I'm not sure what the "true" stringification would be for a DateTime object. The way the stackoverflow question is written, it seems like you're looking for some sort of JSON-specific formatting. AFAIK, there is no one canonical way to stringify a datetime in a JSON data structure. But maybe you're looking for something else?

I've seen people using RFC3339 for stringification in many cases. This works okay, except it loses information because it encodes the TZ offset rather than the TZ *name*.

I could just make something up, but that doesn't seem particularly helpful either. Of course, there are a number of possible ISO8601 formats too. Maybe one of those would make sense.

What it comes down to is that JSON isn't really a specific format, it's a way of structuring a document. In other words, it's up to the API designer to define the very specific contents of the document, including how each data type is represented.

Of course, if I wanted to preserve *all* the info, I'd be inclined to just make a JSON object instead, a la:

```json
{
    "year": 2017,
    "month": 8,
    "day": 2,
    "hour": 16,
    "minute": 30,
    "second": 48,
    "nanosecond": 1234567,
    "locale": "en-US",
    "time_zone": "America/New_York"
}
```

DateTime *already* offers a number of stringification methods, including `datetime`, `strftime`, and `format_cldr`. The latter two offer the flexibility to pick the format you think is best.

This seems like it has some overlap with #35 as well.

All of this is a long way of saying that I'm not inclined to add a new method that would do something very similar to all the other existing stringification methods, and any method I added would be unlikely to solve a general problem.

**Comment by yahermann** [comment]
The format is set upon construction:

    $dt = DateTime->new(
        year => $1,
        month => $2,
        day => $3,
        formatter => DateTime::Format::Strptime->new(
           pattern => '%Y-%m-%d'
           )
        );

so I'm just looking for a way to easily get a "true" string in the previously-specified format, with said string working within the JSON module.  Or maybe this is a specific problem with the JSON module?

As others said, "$dt" or ''.$dt or substr($dt,0), all will get there.  Just looking for cleaner :)

**Comment by autarch** [comment]
Ah, I see. In that case, the "true" way is to force Perl to stringify it for you, a la `q{} . $dt`.

The issue with the `JSON` module is that by default does not accept an object, even if that object overloads stringification. If you enable the `convert_blessed` option, then it will accept an object, but only if that object implements a `TO_JSON` method. As you can see from #35, I couldn't really figure out what the heck such a method should do for `DateTime`.

Arguably, I'd say that JSON should have an option to stringify objects (maybe only if said object explicitly allows stringification). But it doesn't.

Stringification is generally a bit broken in Perl 5. It's a problem because of how the Perl core stringifies everything by default, so you can't tell whether an object explicitly supports stringification without doing gross things. I wrote a [blog post](https://blog.urth.org/2010/10/16/whats-wrong-with-perl-5s-overloading/) that goes into depth about this quite some time ago. It's not really fixable without breaking Perl 5 completely, so we're stuck with it.

As for adding a `stringify` method that does the same thing as `q{} . $dt`, I can see that making sense. There's really no reason that the current method needs to be private. A PR would be welcome.

**Comment by yahermann** [comment]
A PR is where I get stuck, not really understanding the mechanics of git & github, don't hate :).  Just tried it, hope it works.

**Comment by autarch** [comment]
#59

**Comment by autarch** [comment]
#62

**Comment by autarch** [comment]
Done in v1.44
