### ISSUE TITLE
"Invalid local time" exception leaves object instance in dirty state.

### ISSUE THREAD

**Issue by bbkr** [houseabsolute/DateTime.pm#74]
**Steps to reproduce:**

1. Initialize valid datetime.
```perl
my $when = DateTime->new(
    'time_zone' => 'Asia/Damascus',
    'year' => 2018,
    'month' => 3,
    'day' => 1
);
```

2. Hit nonexistent hour exception.
```perl
eval { $when->add( 'days' => 29 ) };
say $@;
# Invalid local time for date in time zone: Asia/Damascus
````

3. Check object state. It looks like everything is fine. Object has pre-exception values.
```perl
say $when;
# 2018-03-01T00:00:00
```

4.  But any operation on it now produces weird results.
```perl
$when->add( 'days' => 1 );
say $when;
# 2018-03-31T00:00:00
```
(expected value is 2018-03-02T00:00:00)

So when nonexistent hour exception was captured object did not revert cleanly to last valid state despite that it shows like it did.

**Expected behavior:**

Object returning to state that it had before disallowed add() operation.

**Nice to have:**

Some flag in add/subtract methods that will produce DWIM result like this:
```
2018-03-01T00:00:00 Asia/Damascus + 28 days = 2018-03-29T00:00:00
2018-03-01T00:00:00 Asia/Damascus + 29 days = 2018-03-30T01:00:00 # produced without exception
2018-03-01T00:00:00 Asia/Damascus + 30 days = 2018-03-31T00:00:00
```

Adding hours is very inconvenient, because:
```
2018-03-01T00:00:00 Asia/Damascus + 29*24 hours = 2018-03-30T01:00:00 # does not throw
2018-03-01T00:00:00 Asia/Damascus + 30*24 hours = 2018-03-31T01:00:00 # meh, now we have 1 hour drift
```

**Comment by autarch** [comment]
Yes, this is definitely a bug.

As far as a "DWIM" flag, that's a little tricky. At the very least, we'd have to define what it does very carefully since there are multiple right answers when the local time doesn't exist (you can either go forward or backward). But implementing this in a way that's not gross might be quite challenging.

**Comment by bbkr** [comment]
You're right. DWIM-ness may not be universal. Not only when considering forward/backward directions but also for minutes and seconds part: `2018-03-01T00:16:32 Asia/Damascus + 29 days = 2018-03-30T01:00:00 or  2018-03-30T01:16:32 ` ? And there is New Zealand that have  02:45 → 03:45 jumps, which may be extra weird when "on nonexistent hour select nearest possible timestamp" algorithm is used.

So let's forget about DWIMness flag. Removing bug that causes DateTime to remain in dirty state after nonexistent hour exception should be enough to close this issue.

**Comment by akarelas** [comment]
For DWIM, I would do this simple solution: to add 1 day, attempt to add it normally, and if it fails, then retry as follows: convert $dt to UTC, add one day, and then convert back to whatever time_zone $dt had.

**Comment by autarch** [comment]
@akarelas That's a good idea. I wonder if it would make sense to just add a `use_utc` flag to the add and subtract methods, or maybe make new methods that force the use of UTC for all math operations. Of course, there are already wrappers like Moonpig that do this, I believe.

**Comment by akarelas** [comment]
I don't know, I think I wouldn't like to use_utc if it used UTC on every date_add even those that wouldn't fail otherwise. Because that would mean add(months => 6) would always change the time to + or - 1 hour, which I believe wouldn't look good on my data. I'd rather have DWIM as above, even if it required typing $DateTime::DWIM = 1; at the top of some module I used, to let DateTime know I want this behaviour.

Of course my new apps store dates in UTC, but on some older one I use local datetimes, and I have overridden the behaviour of DateTime::add_duration there as described above.

The reason I suggested setting $DT::DWIM = 1 (or maybe even the opposite, have it = 1 by default and set it to 0 optionally), is to let other people define their own way to calculate the sum-date on error if they didn't like this one. But I don't really know what's right - I only code on one site that has local DT. You could ask more people I guess.

**Comment by autarch** [comment]
Setting a global is a non-starter. That changes things for every module you use, not just your own code. I can't even imagine the havoc such a thing would wreak.
