### ISSUE TITLE
Upgrade to v1.47 causes Specio fatal exception

### ISSUE THREAD

**Issue by Mike-Parker** [houseabsolute/DateTime.pm#79]
Upgrading from v1.46 to v1.47 causes my script to produce the following fatal exception:

Validation failed for type named Int declared in package Specio::Library::Builtins (/Library/Perl/5.18/Specio/Library/Builtins.pm) at line 163 in sub named (eval) with value 0.7

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Int declared in package Specio::Library::Builtins (/Library/Perl/5.18/Specio/Library/Builtins.pm) at line 163 in sub named (eval) with value 0.7', 'type', 'Specio::Constraint::Simple=HASH(0x7f834c427c70)', 'value', 0.7) called at (eval 210) line 28
DateTime::Duration::_check_multiply_params(0.7, 1) called at /Library/Perl/5.18/darwin-thread-multi-2level/DateTime/Duration.pm line 286
DateTime::Duration::multiply('DateTime::Duration=HASH(0x7f834d828768)', 0.7, 1) called at /Library/Perl/5.18/darwin-thread-multi-2level/DateTime/Duration.pm line 340
DateTime::Duration::_multiply_overload('DateTime::Duration=HASH(0x7f834a2b6cc0)', 0.7, 1) called at cost_profile.pl line 244
main::process_timeline('ARRAY(0x7f8349b79020)', 0, undef, 70) called at cost_profile.pl line 206
main::check_resource_available('HASH(0x7f834f919068)', 'DateTime=HASH(0x7f834a5a05d8)', undef, undef, undef, 70) called at cost_profile.pl line 96

---

Issue is reproducible and is present in v1.48 also. Code works fine in v1.46 and earlier.

**Comment by autarch** [comment]
This is intentional. The changelog for 1.47 says `- DateTime::Duration->multiply now only allows integer multipliers.` The fact that non-integer values were allowed before was a bug, and there's no way it could produce sane results. Nothing in the DateTime internals is actually capable of handling non-integer values, so allowing this in DateTime::Duration never actually made sense.

Maybe there's another way to accomplish what you're trying to do?

**Comment by Mike-Parker** [comment]
That's a real pity as it was really convenient multiplying a duration by 0.7 to determine what 70% of it represented.

I'd appreciate ideas on how this could be achieved another way since there's no overload provided for duration division.

**Comment by autarch** [comment]
It depends on what the duration contains. If it's seconds, then you can do something like `$dt->add( int( $duration->in_units('seconds') * 0.7 ) )`.

If it contains any other unit this gets more challenging since now you'd have to convert from one unit to the other.

But I really need to emphasize that the fact that this worked for you in the past was entirely an accident, and it could easily lead to broken results since nothing actually handled things like "0.7 days" internally.

**Comment by Mike-Parker** [comment]
OK, I've implemented your suggestion and removed my inadvertent dependency upon the bug. I'm now happily running v1.48 without issue.

Many thanks for all your hard work on DateTime - it's a great module and has saved me a hell of a lot of time (no pun intended) over the years.
