### ISSUE TITLE
DateTime::new('DateTime', 'year', '', 'month', undef, 'day', undef, 'time_zone', 'GMT') produces unexpected results:

### ISSUE THREAD

**Issue by philiprbrenan** [houseabsolute/DateTime.pm#95]
DateTime::new('DateTime', 'year', '', 'month', undef, 'day', undef,
'time_zone', 'GMT') produces unexpected results:
```

Use of uninitialized value in scalar assignment at /usr/local/share/perl/5.26.1/Devel/StackTrace.pm line 8
substr outside of string at /usr/local/share/perl/5.26.1/Devel/StackTrace.pm line 84.
Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/local/lib/x86_64-lin
Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named DayOfMonth decl
DateTime::_check_new_params('year', '', 'month', undef, 'day', undef, 'time_zone', 'GMT') called at /usr/l
DateTime::new('DateTime', 'year', '', 'month', undef, 'day', undef, 'time_zone', 'GMT') called at /home/ph
```

**Comment by autarch** [comment]
Could you share the relevant code?

**Comment by philiprbrenan** [comment]
In effect: 
```
    my $date;
    my $dt = DateTime->new(                                                     # Creation date
    year      => substr($date, 0, 4),
    month     => substr($date, 5, 2),
    day       => substr($date, 8, 2),
    time_zone => 'GMT');
```

**Comment by autarch** [comment]
I'm not sure if this is fixable. I can replicate this with much simpler code:

```perl
use strict;
use warnings;

use Devel::Dwarn;

my $date;

foo(
    year      => substr( $date, 0, 4 ),
    month     => substr( $date, 5, 2 ),
    day       => substr( $date, 8, 2 ),
    time_zone => 'GMT',
);

sub foo {
    my %args = @_;
    Dwarn \%args;
}
```

It's odd that the warnings about `substr outside of string` come from inside the `foo()` sub, but I'm guessing that's some sort of Perl optimization where it doesn't actually attempt to retrieve the value of the `substr` call until the containing variable is being reassigned into the hash.

The `Use of uninitialized value within @_ in list assignment` is apparently from the same optimization. This is discussed here - https://stackoverflow.com/questions/31567699/why-does-encode-raise-use-of-uninitialized-value-within.

The warning from `DateTime` is coming from a sub created by `Params::ValidationCompiler`. It would be wrong to make that module filter out `undef` _values_, since depending on the type constraint they could be perfectly valid.

**Comment by philiprbrenan** [comment]
I see - yes - the location of the error is not being correctly reported in an attempt to optimize substr.  I will try reporting this as a perlbug as it is annoying feature (but perhaps not annoying enough).  Thank you for your help.
